feat: sync UK's NIP
jabardigitalservice/office-services pull request #642
Opened 2023-02-28 00:46 UTC by samudra-ajri

## Overview
Update the UK's NIP to be synchronized with Sidebar v2 data.

## Links
- clickup: https://app.clickup.com/t/860pxnnaq

## To Do
- [ ] update env

## Evidence:
project: SIDEBAR
title: feat(doc-headers): crawl sidebar v1
participants: @samudra-ajri @azophy 
screenshot: https://user-images.githubusercontent.com/54126488/221722702-c6d539d1-2cff-4958-a8cf-8ad898a5ecda.png

2023-02-28 00:58 UTC, indraprasetya154 commented on src/.env.example
> +SIDEBARV2_URL=
On next step, maybe we will use api gateway for connecting between v1  v2

2023-02-28 00:58 UTC, indraprasetya154 approved these changes

2023-02-28 01:04 UTC, samudra-ajri commented on src/.env.example
> +SIDEBARV2_URL=
Sure, gass! 🚀

2023-02-28 03:40 UTC, muhamadabduh approved these changes

2023-03-01 01:52 UTC, azophy requested changes

2023-03-01 01:52 UTC, azophy commented on src/routes/api.php
> +    Route::get('/sync/sidebarv2/uk', [SidebarV2SynchronizeUKController::class, '__invoke']);
from my understanding, this route is unprotected right? because this route is pretty sensitive I have a couple suggestion:
1. move this route to below line, so it would use the same auth as Sidebar webhook. this should be pretty secure
2. because currently we dont actually need to run this command more than once, we could actually move this code into an artisan command which could be run by devops when the needs arise. 

I think option no 2 is the better approac, but obviously it need more works on your side .😅 So I dont really mind if you choose option 1. At least its best if we dont leave this endpoint unprotected.

2023-03-01 01:52 UTC, azophy commented on src/app/Models/Organization.php
> +class Organization extends Model
I think the term `Organization` may cause confusion in the future. could you rename it to something more explicit like `OrganizationMapping` ?

2023-03-01 01:52 UTC, azophy commented on src/app/Http/Controllers/V1/SidebarV2SynchronizeUKController.php
> +                $statements .= "WHEN PrimaryRoleId = '$roleId' THEN '$nip' ";
nice 👍

2023-03-01 02:33 UTC, samudra-ajri commented on src/app/Models/Organization.php
> +class Organization extends Model
Sure, here it is https://github.com/jabardigitalservice/office-services/pull/642/commits/abd796679510cbc8ab91b173ef73954ef74cba5b 😁

2023-03-01 02:34 UTC, samudra-ajri commented on src/routes/api.php
> +    Route::get('/sync/sidebarv2/uk', [SidebarV2SynchronizeUKController::class, '__invoke']);
Thank you for the suggestion, Mas..
For this time, let me choose the first option. 😁 

modified: https://github.com/jabardigitalservice/office-services/pull/642/commits/45420d4a70a53a4b0e488055d94155d14f7b00a2

2023-03-01 03:11 UTC, azophy approved these changes
nice nuhun2 jri 👍

2023-03-01 03:21 UTC, merged