feat(document-distribution): create distribution api for sidebar v2
jabardigitalservice/office-services pull request #660
Opened 2023-03-29 02:37 UTC by indraprasetya154

## Overview
feat(document-distribution): create distribution api for sidebar v2

## Links
- clickup: https://app.clickup.com/t/860q2ernf

## Evidence:
project: SIDEBAR
title: feat(document-distribution): create distribution api for sidebar v2
participants: @indraprasetya154

2023-03-29 03:59 UTC, azophy requested changes

2023-03-29 03:59 UTC, azophy commented on src/routes/api.php
> +    Route::post('/document-distribution', [DocumentDistributionController::class, '__invoke']);
I thinks its better to move this route inside `SidebarWebhookMiddleware` so it would enable the same auth as other webhook. This endpoint is quite sensitive

2023-03-29 03:59 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $this->people   = (object) $request->input('people');
same as [this comment](https://github.com/jabardigitalservice/office-service-v2/pull/214/files#r1151365887): to avoid confusion, I thinks its better to name this field `creator`

2023-03-29 03:59 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +                    'inbox_id' => $this->inboxId
could we also include document_id from v2 in here?

2023-03-29 03:59 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $inbox->sidebar_v2_metadata = json_encode($this->document);
I forgot. Have we added migration for this 2 columns?

2023-03-29 04:05 UTC, azophy requested changes

2023-03-29 04:05 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $time = parseDateTimeFormat(Carbon::now(), 'dmY') . '_' . parseDateTimeFormat(Carbon::now(), 'His');
rather than this, isnt it easier to just use `format()` method from carbon?

```suggestion
        $time = Carbon::now()->format('Ymd_His');
```

2023-03-29 04:05 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $pdfFile = file_get_contents(Storage::path($pdfName), 'r');
couldn't we just do this?

```suggestion
        $pdfFile = file_get_contents(file_get_contents($this->document->file['path']));
```

2023-03-29 06:50 UTC, indraprasetya154 commented on src/routes/api.php
> +    Route::post('/document-distribution', [DocumentDistributionController::class, '__invoke']);
Fixed here mas https://github.com/jabardigitalservice/sidebar-internal-gateway/pull/11#discussion_r1151464996
[ac2cd01](https://github.com/jabardigitalservice/office-services/pull/660/commits/ac2cd01b236c2c65d64135306feff0f8951daf48)

2023-03-29 06:57 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $this->people   = (object) $request->input('people');
Fixed here mas [07c299a](https://github.com/jabardigitalservice/office-services/pull/660/commits/07c299aa3e7b4e65c4cd9f1c27a3c27fc51f0ece)
also here 😄 
https://github.com/jabardigitalservice/office-service-v2/pull/214#discussion_r1151468939

2023-03-29 07:00 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $inbox->sidebar_v2_metadata = json_encode($this->document);
Already added here mas [ab2a462](https://github.com/jabardigitalservice/office-services/pull/660/commits/ab2a4620cc602b52f1bc44ec9228f8f791758301)

2023-03-29 07:03 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $pdfFile = file_get_contents(Storage::path($pdfName), 'r');
or you mean we didn't need to save file and use file upload with `file_get_contents` return, CMIIW

2023-03-29 07:43 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $pdfFile = file_get_contents(Storage::path($pdfName), 'r');
this @indraprasetya154 

> or you mean we didn't need to save file and use file upload with file_get_contents return, CMIIW

from my understanding, the code here only need to download the file to be passed on to sikd-website. so I think it didn't actually need to be stored on hard drive. cmiiw

2023-03-29 10:29 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $time = parseDateTimeFormat(Carbon::now(), 'dmY') . '_' . parseDateTimeFormat(Carbon::now(), 'His');
if we didnt use the parse date time format, it will be on gmt format

2023-03-29 11:08 UTC, azophy commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $time = parseDateTimeFormat(Carbon::now(), 'dmY') . '_' . parseDateTimeFormat(Carbon::now(), 'His');
i see. how about this then?

```suggestion
        $time = parseDateTimeFormat(Carbon::now(), 'dmY_His');
```

2023-03-29 14:17 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $time = parseDateTimeFormat(Carbon::now(), 'dmY') . '_' . parseDateTimeFormat(Carbon::now(), 'His');
naaah i now what you mean mas. thanks for suggestion

2023-03-29 14:27 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $time = parseDateTimeFormat(Carbon::now(), 'dmY') . '_' . parseDateTimeFormat(Carbon::now(), 'His');
fixed here [a6bd0b0](https://github.com/jabardigitalservice/office-services/pull/660/commits/a6bd0b0b0e6610f5b0d4cb38b9431284444443d2)

2023-03-29 14:34 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $pdfFile = file_get_contents(Storage::path($pdfName), 'r');
I tried on my local and your suggestion is running well, thanks mas
change here [cded7c0](https://github.com/jabardigitalservice/office-services/pull/660/commits/cded7c0f22454415120f96b5a9787a12d7bf0228)

2023-03-29 14:40 UTC, azophy approved these changes
niceee 👍

2023-03-30 00:46 UTC, fajarhikmal214 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $inboxFile->Id_Dokumen      = $this->document->file['qrcode'];
I am sure it's `code` not `qrocode`

2023-03-30 01:37 UTC, indraprasetya154 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $inboxFile->Id_Dokumen      = $this->document->file['qrcode'];
naaah my bad i think it use qrcode column, fixed here kang @fajarhikmal214  [2b38428](https://github.com/jabardigitalservice/office-services/pull/660/commits/2b38428d619d4c8ced436420603736d7172b19d9)

2023-03-30 01:40 UTC, fajarhikmal214 commented on src/app/Http/Controllers/V1/DocumentDistributionController.php
> +        $inboxFile->Id_Dokumen      = $this->document->file['qrcode'];
Thanks

2023-03-30 01:40 UTC, fajarhikmal214 approved these changes

2023-03-30 02:28 UTC, samudra-ajri approved these changes

2023-03-30 02:56 UTC, merged